[template]
src = "grpc.boot.tmpl"
dest = "/opt/minion/etc/featuresBoot.d/grpc.boot"
keys = [
    "/ipc/grpc"
]
reload_cmd = "/opt/minion/confd/scripts/remove-if-empty /opt/minion/etc/featuresBoot.d/grpc.boot"
