[template]
src = "org.opennms.core.ipc.rpc.kafka.cfg.tmpl"
dest = "/opt/minion/etc/org.opennms.core.ipc.rpc.kafka.cfg"
keys = [
    "/ipc/rpc/kafka"
]
reload_cmd = "/opt/minion/confd/scripts/remove-if-empty /opt/minion/etc/org.opennms.core.ipc.rpc.kafka.cfg"
