[template]
src = "org.opennms.core.ipc.grpc.client.cfg.tmpl"
dest = "/opt/minion/etc/org.opennms.core.ipc.grpc.client.cfg"
keys = [
    "/ipc/grpc"
]
reload_cmd = "/opt/minion/confd/scripts/remove-if-empty /opt/minion/etc/org.opennms.core.ipc.grpc.client.cfg"
